#!/usr/bin/env python

import argparse
import datetime
import lxml.etree
import lxml.html
import os
import os.path
import shutil
import subprocess
import tempfile

def extract_javascript(html, root):
  scripts = ""
  transactions = html.xpath("//script[@type='text/javascript']")
  for transaction in transactions:
    src = os.path.join(root, transaction.get("src"))
    with open(src) as script:
      scripts = scripts + "\n" + script.read()
    transaction.drop_tree()

  filtered = ""
  for line in scripts.split("\n"):
    if line.find('"use strict";') != 0:
      filtered = filtered + "\n" + line

  return filtered

def extract_tags(html, tag, key, root):
  scripts = ""
  transactions = html.xpath(tag)
  for transaction in transactions:
    src = os.path.join(root, transaction.get(key))
    with open(src) as script:
      scripts = scripts + "\n" + script.read()
    transaction.drop_tree()
  return scripts

def copy_directory(source, destination):
  name = os.path.basename(os.path.abspath(source))
  shutil.copytree(source, os.path.join(destination, name))

def append_javascript(html, script):
  body = html.find('body')
  source = "<script type='text/javascript' type='text/css'>" + script + "</script>"
  link = lxml.html.fromstring(source).find('.//script')
  body.append(link)

def append_style(html, style):
  head = html.find('head')
  tag = "<style>" + style + "</style>"
  style = lxml.html.fromstring(tag).find('.//style')
  head.append(style)

def yuicompressor(contents, suffix):
  temp = tempfile.mktemp(suffix=suffix)
  with open(temp, 'w') as f:
    f.write(contents)
  output = subprocess.check_output(['yuicompressor', temp])
  os.unlink(temp)
  return output

def main():
  parser = argparse.ArgumentParser(description = "Generate the minified Game Play HTML file")
  parser.add_argument("project", help = "root of the project")
  parser.add_argument("settings", help = "settings file")
  options = parser.parse_args()

  project_dir = os.path.abspath(options.project)
  source_dir = os.path.join(project_dir, "src")
  build_dir = os.path.join(project_dir, "build")
  input_file = os.path.join(source_dir, "index.html")
  output_file = os.path.join(build_dir, "index.html")
  images_dir = os.path.join(source_dir, "images")
  defaults_dir = os.path.join(source_dir, "defaults")
  manifest_file = os.path.join(build_dir, "cache.manifest")
  settings_dest = os.path.join(build_dir, "settings.json")

  # build
  if os.path.exists(build_dir):
    shutil.rmtree(build_dir)
  os.mkdir(build_dir)

  # index.html
  contents = None
  with open(input_file) as f:
    contents = f.read()
  html = lxml.html.fromstring(contents)

  # script
  script = extract_tags(html, "//script[@type='text/javascript']", "src", source_dir)
  script = yuicompressor(script, '.js')
  append_javascript(html, script)

  # style
  style = extract_tags(html, "//link[@type='text/css']", "href", source_dir)
  style = yuicompressor(style, '.css')
  append_style(html, style)

  with open(output_file, 'w') as f:
    f.write("<!DOCTYPE html>\n");
    f.write(lxml.html.tostring(html))

  # images
  copy_directory(images_dir, build_dir)
  
  # defaults
  copy_directory(defaults_dir, build_dir)

  # settings
  shutil.copy(options.settings, settings_dest)

  # manifest
  manifest = []
  for root, subdirs, files in os.walk(build_dir):
    for file in files:
      if file.find('.') != 0:
        manifest.append(os.path.relpath(os.path.join(root, file), build_dir))
  with open(manifest_file, 'w') as f:
    f.write("CACHE MANIFEST\n")
    f.write("# %s\n" % str(datetime.datetime.now()))
    f.write("CACHE:\n")
    f.write("\n".join(map(lambda x: x, manifest)))
    f.write("\n")

if __name__=='__main__':
  main()