#!/bin/bash

set -e
set -u

configuration=$1

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_dir=$( dirname "$script_dir" )
build_dir="$root_dir/build"

if [[ ! -f "$configuration" ]]; then
    echo "Unable to find configuration file '$1'."
    exit 1
fi

remote=$( cat "$configuration" | python -c "import json; import sys; print json.load(sys.stdin)['remote']" )

echo "Uploading to '$remote'..."

python "$script_dir/build" "$configuration"

rsync -avPe ssh \
    "$build_dir"/*.{html,txt} \
    "$build_dir"/*.manifest \
    "$build_dir"/images \
    "$build_dir"/defaults \
    "$remote"
