#!/usr/bin/env python

import argparse
import os
import SimpleHTTPServer
import SocketServer

import paths


def main():
    parser = argparse.ArgumentParser(description="Run a local Game Play server.")
    parser.add_argument("--port", default=8000, type=int, help="Listening port.")
    options = parser.parse_args()

    httpd = SocketServer.TCPServer(("", options.port), SimpleHTTPServer.SimpleHTTPRequestHandler)
    print "Serving on http://127.0.0.1:%d..." % options.port
    os.chdir(paths.BUILD_DIR)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
