#!/usr/bin/env python

import sys

YELLOW = "\033[1;33m"
RED = "\033[1;31m"
GREEN = "\033[32m"

RESET = "\033[m"

for line in sys.stdin:
    line = line.strip()
    color = ""
    if "SUCCESS" in line:
        color = GREEN
    elif "FAIL" in line or "error:" in line:
        color = RED
    print "%s%s%s" % (color, line, RESET)
